config/routes.rb
Messenger::Application.routes.draw do
  devise_for :users

  resources :messages
  
  root :to => 'messages#index'
  

end

app/models/message.rb
class Message < ActiveRecord::Base
  attr_accessible :content, :talker
  validates :content, :length => { :maximum => 10000 }
  scope :query_keyword, lambda{
    |keyword| where('talker like :q or content like :q', :q => "%#{keyword}%")
  }
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :username, :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
  validates :username, :uniqueness => true

  # Virtual attribute for authenticating by either username or email
  # This is in addition to a real persisted field like 'username'
  attr_accessor :login
  attr_accessible :login
  
  def self.find_first_by_auth_conditions(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions).where(["lower(username) = :value OR lower(email) = :value", { :value => login.downcase }]).first
    else
      where(conditions).first
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  @@keyword = nil
  def index
    @message = Message.new
    @messages = Message.query_keyword(params[:keyword]).order("created_at DESC").page(params[:page]).per(10)
    if params[:keyword].present?
      @@keyword = @keyword = params[:keyword]
    else
      @@keyword = @keyword = nil
    end
  end
  
  def create
    @message = Message.new(params[:message])
    if 0 < @message.content.length
      @message.talker = current_user.username
      if @message.save
        redirect_to messages_path(:keyword => @@keyword)
      else
        redirect_to messages_path, notice: 'Message Failed.'
      end
    else
      @message = nil
      redirect_to messages_path
    end
  end
  
  def edit
    @message = Message.find(params[:id])
  end
  
  def update
    @message = Message.find(params[:id])
    if current_user.username != @message.talker
      redirect_to messages_path, notice: "Can not edit other user's message."
      return
    end
    if @message.update_attributes(params[:message])
      redirect_to messages_path, notice: "Message Updated."
    else
      render action: 'edit'
    end
  end
  
  def destroy
    @message = Message.find(params[:id])
    if current_user.username != @message.talker
      redirect_to messages_path, notice: "Can not delete other user's message."
      return
    end
    @message.destroy
    redirect_to messages_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Messenger</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="navbar navbar-fixed-top">
    <div class="navbar-inner">
      <div class="container">
        <div class="nav-collapse">
          <ul class="nav">
            <% if user_signed_in? %>
              <li><%= link_to current_user.username, messages_path %></li>
            <% end %>
            <li><%= link_to "Messages", messages_path %></li>
            <% if user_signed_in? %>
              <li><%= link_to "Logout", destroy_user_session_path, :method => 'delete' %></li>
              <li><%= link_to "Setting", edit_user_registration_path %></li>
              <li>
                <%= form_tag({:controller => 'messages', :action => 'index'}, {:method => :get, :id => :id_search_form}) do %>
                  <%= search_field_tag :keyword, @keyword %>
                <% end %>
              </li>
            <% else %>
              <li><%= link_to "SignIn", new_user_session_path %></li>
              <li><%= link_to "SignUp", new_user_registration_path %></li>
            <% end %>
          </ul>
        </div>
      </div>
    </div>
  </div>
  <div class="container">
    <%= yield %>
  </div>
</body>
</html>

app/views/messages/_form.html.erb
<%= form_for(@message) do |f| %>
  <% if @message.errors.any? %>
    <ul>
      <% @message.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  <% end %>
  
  <div class="field">
    <%# f.label :content %>
    <%= f.text_area :content, :class => "span12", :rows => 3 %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/messages/edit.html.erb
<h1>Edit Message</h1>
<%= render 'form' %>
<%= link_to 'timeline', messages_path %>

app/views/messages/index.html.erb
<h1>Timeline</h1>
<div id="notice"><%= notice %></div>
<%= form_for(@message) do |f| %>
  <div class="field">
    <%# f.label :content %>
    <%= f.text_area :content, :class => "span12", :rows => 3 %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
<ul>
  <% @messages.each do |message| %>
    <li>
      <%= message.talker %>
      <% if user_signed_in? %>
        <% if current_user.username == message.talker %>
          <%= link_to 'Edit', edit_message_path(message) %>
          <%= link_to 'Delete', message, :confirm => 'Are you sure?', :method => :delete %>
        <% end %>
      <% end %>
      <%= simple_format(message.content) %>
    </li>
  <% end %>
  <%= paginate @messages %>
</ul>

<script>
$(function() {
  setTimeout(
    function() { $('#notice').fadeOut("slow"); },
    2000);
});
</script>